name: Backend Docker Deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Run backend tests
        run: ./gradlew test
        working-directory: backend

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: az acr login --name acrtaskapp

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/task-api:${{ github.sha }} ./backend

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/task-api:${{ github.sha }}

      - name: Deploy container to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: "webapp-task-api-dev"
          slot-name: "staging"
          images: "${{ secrets.ACR_LOGIN_SERVER }}/task-api:${{ github.sha }}"
